### ISSUE TITLE
Replace use of ap_log_rdata()

### ISSUE THREAD

**Issue by frozencemetery** [gssapi/mod_auth_gssapi#186]
#185 allowed building when `ap_log_rdata()` is missing.  However, this function isn't insanely complicated - all it seems to do is: log a string (label), then log another string (data), escaped where nonprintable, along with a hexdump of that string.  Replacing it would be very doable - we could also format it more nicely than the three lines that get produced on every call to mag_set_required_name_attr() right now.

**Comment by simo5** [comment]
@frozencemetery is this still relevant ?

**Comment by frozencemetery** [comment]
I no longer care about el7 personally and would therefore be inclined to close.

**Comment by simo5** [comment]
agreed
