### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by adfel70** [gssapi/mod_auth_gssapi#221]
We are using mod_gssapi to add Kerberos authentication to our server and it works as expected, but we are issuing CORS error while trying to execute requests from javascript code.
We added the expected **Access-Control-Allow-Origin** header with our domain to Apache's configuration as follow:

```
Header set Access-Control-Allow-Origin "http://desired.server"
```

but still no luck.
While investigating the problem we saw that the header is added only to the **second** response (the final response), and not during the negotiation handshake:

```
// first request and server response (Access-Control-Allow-Origin header is missing)
< HTTP/1.1 401 Unauthorized
< WWW-Authenticate: Negotiate

//Second request and response
> Authorization: Negotiate XXXX... USER_TOKEN_VALUE ...XXXX
< HTTP/1.1 200 OK
< WWW-Authenticate: Negotiate ....
< Access-Control-Allow-Origin: http://desired.server
```
Our guess is that the browser blocks the request during the hanshake, not executing the second request at all. Is there a way to set the missing header also during the handshake?

Thanks.

**Comment by simo5** [comment]
I think you should look at Early and Late processing:
http://httpd.apache.org/docs/current/mod/mod_headers.html

I guess that when returning an error late processing is shortcut out.
By using early processing int he /location directive where you configure mod_auth_gssapi may do what you want.

But this is really not a mod_auth_gssapi issue, so I am going to close this for now.
Please reopen if you think there is an actual bug in the way mod_auth_gssapi handles authentication that influences mod_headers in improper ways.
