### ISSUE TITLE
Delegation Problem With Users From Different Realm

### ISSUE THREAD

**Issue by canth1** [gssapi/mod_auth_gssapi#233]
Hello, I have a problem that I can't seem to solve and I believe that the issue is with mod_auth_gssapi as I can accomplish what I'm trying to do on the command line.

First some background information.

I have a large Active Directory deployment with a single forest, and multiple domains. All domains have two-way transitive trusts, so this isn't an AD trust isse.

I have an AD service account in a domain (let's call it **DOMAIN-A**) that I used to create a ketytab file, and mod_auth_gssapi uses that keytab in GssapiCredStore. This works perfectly. Users visiting from any domain in the forest have their $_SERVER['REMOTE_USER'] PHP variable populated with their AD userPrincipalName. Everything is great so far.

Now, I've enable delegation with the following config:

```
GssapiCredStore ccache:FILE:/xxxx/xxx
GssapiCredStore client_keytab:/xxx/xxx
GssapiCredStore keytab:/xxx/xxx
GssapiDelegCcacheDir /xxx/xxx
GssapiUseS4U2Proxy On
```

I'm seeing the ccache files of visiting users being created correctly in the ccache folder. So that's good so far. I'm also getting the PHP variable $_SERVER['KRB5CCNAME'] correctly. And in my code i'm setting that as an environment variable: 

`putenv('KRB5CCNAME=' . $_SERVER['KRB5CCNAME']);`

This actually works great for users from **DOMAIN-A** as it's using their credentials to log into a SQL Server.

The problem is, any other users NOT from **DOMAIN-A** get an error.

Here is the SQL Server error:

```
[Microsoft][ODBC Driver 17 for SQL Server]SSPI Provider: KDC can't fulfill requested option
[Microsoft][ODBC Driver 17 for SQL Server]Cannot generate SSPI context
```

 If I enable KRB5_TRACE, here is the error from there:

`TGS request result: -1765328371/KDC can't fulfill requested option`

After some investigation, I've figured out what the issue is, and it seems to be the contents of the ccache files.

So a user from **DOMAIN-A** will have their ccache file look like this:
```
klist -c XXXXXXXXXX@DOMAIN-A

Ticket cache: FILE:XXXXXXXXXX@DOMAIN-A
Default principal: XXXXXXXXXX@DOMAIN-A

Valid starting       Expires              Service principal
09/15/2020 19:59:47  09/16/2020 05:59:47  krbtgt/DOMAIN-A@DOMAIN-A
        renew until 09/22/2020 19:59:47
09/15/2020 19:59:47  09/16/2020 05:59:47  MSSQLSvc/xxxxxxxxxx@DOMAIN-A
        renew until 09/22/2020 19:59:47
```

They have gotten a ticket for the SQL Server correctly, and everything works.

The contents of a ccache file from a user from **DOMAIN-B** look like this:

```
klist -c XXXXXXXXXX@DOMAIN-B

Ticket cache: FILE:XXXXXXXXXX@DOMAIN-B
Default principal: XXXXXXXXXX@DOMAIN-B

Valid starting       Expires              Service principal
09/15/2020 20:23:34  09/15/2020 21:11:51  XXXXXXXXXX@DOMAIN-A
        renew until 09/22/2020 11:11:51
09/15/2020 19:59:47  09/16/2020 05:59:47  MSSQLSvc/xxxxxxxxxx:1433@DOMAIN-A
        for client XXXXXXXXXX@DOMAIN-A, renew until 09/22/2020 19:59:47
09/15/2020 19:59:47  09/16/2020 05:59:47  krbtgt/DOMAIN-A@DOMAIN-A
        for client XXXXXXXXXX@DOMAIN-A, renew until 09/22/2020 19:59:47
```

And that doesn't seem to look right compared to a klist if I do the following on the command line:

```
kinit XXXXXXXXXX@DOMAIN-B

klist

Ticket cache: FILE:/tmp/krb5cc_0
Default principal: XXXXXXXXXX@DOMAIN-B

Valid starting       Expires              Service principal
09/15/2020 20:41:10  09/16/2020 06:41:10  krbtgt/DOMAIN-B@DOMAIN-B
        renew until 09/22/2020 20:40:56

kvno MSSQLSvc/xxxxxxxxxx

klist

Ticket cache: FILE:/tmp/krb5cc_0
Default principal: XXXXXXXXXX@DOMAIN-B

Valid starting       Expires              Service principal
09/15/2020 20:41:10  09/16/2020 06:41:10  krbtgt/DOMAIN-B@DOMAIN-B
        renew until 09/22/2020 20:40:56
09/15/2020 20:45:32  09/16/2020 06:41:10  MSSQLSvc/xxxxxxxxxx:@DOMAIN-A
        renew until 09/22/2020 20:40:56
```

The biggest thing that I think is the issue is that through mod_auth_gssapi the krbtgt seems to be for the wrong realm:

krbtgt/DOMAIN-A@DOMAIN-A instead of krbtgt/DOMAIN-B@DOMAIN-B

And if I put this in my code using the above correct ticket:

`putenv('KRB5CCNAME=FILE:/tmp/krb5cc_0');`

It works as expected.

So, I've tried everything that I can, and I'm not sure if this is a mod_auth_gssapi issue or a kerberos configuration issue?

**Comment by iboukris** [comment]
> TGS request result: -1765328371/KDC can't fulfill requested option

This looks like a configuration issue, did you test the same on windows? perhaps the presented ticket isn't forwardable although there should be no reason for that (it isn't required for RBCD), or maybe the user has the not-delegated flag.

What version of the krb5 libs are you using?
How did you configure constrained-delegation, traditional or resource-based?
Can you post more of the KRB5_TRACE?
Assuming the HTTP service is in DOMAIN-A, where is the target SQL service, in DOMAIN-A as well?

The ccache looks rather fine (as far as one can see, please substitute with consistent names rather than xxx) , in S4U2SProxy the ccache should include a tgt for the impersonator, that is the HTTP service who is from DOMAIN-A I assumed.

**Comment by canth1** [comment]
Thanks for the reply...

When you say test on Windows, what exactly do you mean by that?

As for the Kerberos libraries, I'm using the latest on Ubuntu 16.04, which is 1.13.2 - https://packages.ubuntu.com/xenial/krb5-user

As for delegation, I have the "Trust this user for delegation to any service" option selected for the service account in the keytab, which I believe is unconstrained delegation.

I'll generate the KRB5_TRACE again, and post more of it.

Yes, both the HTTP service is in DOMAIN-A as is the SQL server.

I'll update the ccache contents to be more readable.

**Comment by simo5** [comment]
@canth1 isf you are after *unconstrained* delegation then you do not need (and probably want to oimt to avoid confusion) these two configuration directives:
GssapiCredStore client_keytab:/xxx/xxx
GssapiUseS4U2Proxy On

These two options are needed only when *constrained* delegation is expected (aka S4U2Proxy).

**Comment by canth1** [comment]
Here is the full KRB5_TRACE of a user from another domain that can't logon to the SQL Server.

MSSQLSvc/sql-server:1433@DOMAIN-A is the SQL Server in DOMAIN-A
DOMAIN-B-USER@DOMAIN-B is the user from another AD domain that can't log into the SQL Server.
DOMAIN-A-SERVICE-ACCOUNT@DOMAIN-A is the account that's in the Apache server's keytab file
FILE:DOMAIN-B-USER@DOMAIN-B is the ccache file created by mod_auth_gssapi

```
[58641] 1600276789.31161: ccselect can't find appropriate cache for server principal MSSQLSvc/sql-server:1433@DOMAIN-A
[58641] 1600276789.31262: Retrieving DOMAIN-B-USER@DOMAIN-B -> DOMAIN-A-SERVICE-ACCOUNT@DOMAIN-A from FILE:DOMAIN-B-USER@DOMAIN-B with result: 0/Success
[58641] 1600276789.31271: Getting credentials DOMAIN-A-SERVICE-ACCOUNT@DOMAIN-A -> MSSQLSvc/sql-server:1433@DOMAIN-A using ccache FILE:DOMAIN-B-USER@DOMAIN-B
[58641] 1600276789.31334: Retrieving DOMAIN-A-SERVICE-ACCOUNT@DOMAIN-A -> krbtgt/DOMAIN-A@DOMAIN-A from FILE:DOMAIN-B-USER@DOMAIN-B with result: 0/Success
[58641] 1600276789.31341: Starting with TGT for client realm: DOMAIN-A-SERVICE-ACCOUNT@DOMAIN-A -> krbtgt/DOMAIN-A@DOMAIN-A
[58641] 1600276789.31346: Requesting tickets for MSSQLSvc/sql-server:1433@DOMAIN-A, referrals on
[58641] 1600276789.31360: Generated subkey for TGS request: aes256-cts/031E
[58641] 1600276789.31385: etypes requested in TGS request: aes256-cts, aes128-cts, des3-cbc-sha1, rc4-hmac, camellia128-cts, camellia256-cts
[58641] 1600276789.31476: Encoding request body and padata into FAST request
[58641] 1600276789.31683: Sending request (11094 bytes) to DOMAIN-A
[58641] 1600276789.37652: Resolving hostname DOMAIN-A-KDC.
[58641] 1600276789.39655: Sending initial UDP request to dgram DOMAIN-A-KDC:88
[58641] 1600276789.50377: Received answer (98 bytes) from dgram DOMAIN-A-KDC:88
[58641] 1600276789.51142: Response was not from master KDC
[58641] 1600276789.51165: Request or response is too big for UDP; retrying with TCP
[58641] 1600276789.51170: Sending request (11094 bytes) to DOMAIN-A (tcp only)
[58641] 1600276789.61576: Resolving hostname DOMAIN-A-KDC.
[58641] 1600276789.62463: Initiating TCP connection to stream DOMAIN-A-KDC:88
[58641] 1600276789.73081: Sending TCP request to stream DOMAIN-A-KDC:88
[58641] 1600276789.92035: Received answer (399 bytes) from stream DOMAIN-A-KDC:88
[58641] 1600276789.92067: Terminating TCP connection to stream DOMAIN-A-KDC:88
[58641] 1600276789.94263: Response was not from master KDC
[58641] 1600276789.94313: Decoding FAST response
[58641] 1600276789.94378: TGS request result: -1765328371/KDC can't fulfill requested option
[58641] 1600276789.94389: Requesting tickets for MSSQLSvc/sql-server:1433@DOMAIN-A, referrals off
[58641] 1600276789.94410: Generated subkey for TGS request: aes256-cts/7D0D
[58641] 1600276789.94459: etypes requested in TGS request: aes256-cts, aes128-cts, des3-cbc-sha1, rc4-hmac, camellia128-cts, camellia256-cts
[58641] 1600276789.94588: Encoding request body and padata into FAST request
[58641] 1600276789.94848: Sending request (11095 bytes) to DOMAIN-A (tcp only)
[58641] 1600276789.97602: Resolving hostname DOMAIN-A-KDC.
[58641] 1600276789.99029: Initiating TCP connection to stream DOMAIN-A-KDC:88
[58641] 1600276789.109473: Sending TCP request to stream DOMAIN-A-KDC:88
[58641] 1600276789.128166: Received answer (399 bytes) from stream DOMAIN-A-KDC:88
[58641] 1600276789.128202: Terminating TCP connection to stream DOMAIN-A-KDC:88
[58641] 1600276789.129468: Response was not from master KDC
[58641] 1600276789.129503: Decoding FAST response
[58641] 1600276789.129552: TGS request result: -1765328371/KDC can't fulfill requested option

```

**Comment by iboukris** [comment]
Oh, so for user from domain-a you are using unconstrained delegation, which works because the client sends his TGT, but it doesn't work for a user from another realm so it tries S4U2Proxy. You need to configure Windows DCs to allow unconstrained delegation in cross-realm so they'll send a tgt, take a look here (although for a single forest it should have been fine by default) :
https://support.microsoft.com/en-us/help/4490425/updates-to-tgt-delegation-across-incoming-trusts-in-windows-server

**Comment by canth1** [comment]
Yeah, that seems like it might be a solution, except that article talks about cross forest, and in my environment this is all one forest where all domains trust each other with two way transitive trust.

Also, above when you said to remove:

```
GssapiCredStore client_keytab:/xxx/xxx
GssapiUseS4U2Proxy On
```

I get:

```
[Microsoft][ODBC Driver 17 for SQL Server]SSPI Provider: No Kerberos credentials available
[Microsoft][ODBC Driver 17 for SQL Server]Cannot generate SSPI context
```

Because there isn't anything in $_SERVER['KRB5CCNAME']

**Comment by canth1** [comment]
Also, here is a more readable version of the contents of the ccaches:

```
klist -c DOMAIN-A-SERVICE-ACCOUNT@DOMAIN-A

Ticket cache: FILE:DOMAIN-A-SERVICE-ACCOUNT@DOMAIN-A
Default principal: DOMAIN-A-SERVICE-ACCOUNT@DOMAIN-A

Valid starting       Expires              Service principal
09/16/2020 13:46:03  09/16/2020 23:46:03  krbtgt/DOMAIN-A@DOMAIN-A
        renew until 09/23/2020 13:46:03
```

```
klist -c DOMAIN-B-USER@DOMAIN-B

Ticket cache: FILE:DOMAIN-B-USER@DOMAIN-B
Default principal: DOMAIN-B-USER@DOMAIN-B

Valid starting       Expires              Service principal
09/16/2020 12:38:14  09/16/2020 20:07:03  DOMAIN-A-SERVICE-ACCOUNT@DOMAIN-A
        renew until 09/23/2020 10:07:03
09/16/2020 13:46:03  09/16/2020 23:46:03  krbtgt/DOMAIN-A@DOMAIN-A
        for client DOMAIN-A-SERVICE-ACCOUNT@DOMAIN-A, renew until 09/23/2020 13:46:03
```

**Comment by iboukris** [comment]
Yeah, this looks as expected, try using a more updated version of krb5 libs, but it is most likely a configuration problem on AD side.

**Comment by simo5** [comment]
> Yeah, that seems like it might be a solution, except that article talks about cross forest, and in my environment this is all one forest where all domains trust each other with two way transitive trust.
> 
> Also, above when you said to remove:
> 
> ```
> GssapiCredStore client_keytab:/xxx/xxx
> GssapiUseS4U2Proxy On
> ```
> 
> I get:
> 
> ```
> [Microsoft][ODBC Driver 17 for SQL Server]SSPI Provider: No Kerberos credentials available
> [Microsoft][ODBC Driver 17 for SQL Server]Cannot generate SSPI context
> ```
> 
> Because there isn't anything in $_SERVER['KRB5CCNAME']

This is *exactly* why you should remove "GssapiUseS4U2Proxy On", so then you immediately see that your client has not delegated credentials to your HTTP server, instead of getting synthetized credentials that cannot work.

What "GssapiUseS4U2Proxy On" does is creating a credential with the krbtgt of your HTTP server principal and an evidence ticket from the connecting user. These are to be used in *constrained delegation* schemes. And are useless and "misleading" to you otherwise.

Given you want to use unconstrained delegation from your clients, you should not "mess up" your server with credentials you cannot use. It will help you better understand the problem.

**Comment by canth1** [comment]
Ok, thanks everyone for the help and direction. I'm going to switch my service account to "Trust this user for delegation to specified services only" and add our SQL server service account to the list and see if that fixes the issue.

**Comment by canth1** [comment]
Just an update on this. Switching our service account to constrained delegation fixed the issue for clients from a different realm than the server. So thinks for all the help and direction! I really appreciate it!

**Comment by simo5** [comment]
Glad to hear you found a solution and the problem is not in the module.
