### ISSUE TITLE
Is there support for the equivalent of KrbVerifyKDC off

### ISSUE THREAD

**Issue by tparkercbn** [gssapi/mod_auth_gssapi#251]
I have a bunch of QA and Dev servers that currently run mod_auth_kerb on CentOS 7 that I am migrating to mod_auth_gssapi on CentOS8.  

With mod_auth_kerb I can set: KrbVerifyKDC off which means that I don't have to provision a keytab on all these dev/qa servers.  

Is there a way to do the same with mod_auth_gssapi?

Thanks

**Comment by simo5** [comment]
Is this using the fallback to Basic Auth?
