### ISSUE TITLE
RFC 9266: Channel Bindings for TLS 1.3 support

### ISSUE THREAD

**Issue by Neustradamus** [gssapi/mod_auth_gssapi#270]
Can you add the support of RFC 9266: Channel Bindings for TLS 1.3?
- https://datatracker.ietf.org/doc/html/rfc9266

Little details, to know easily:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3

Thanks in advance.

**Comment by simo5** [comment]
We'd have to support Channel Bindings at all first.

@Neustradamus please do at least basic research before spamming all projects you can find with the same request ...
